version: "2"

services:
  ucm-influxdb:
    image: influxdb:1.8
    container_name: ucm-influxdb
    ports:
      - 8086:8086
    volumes:
      - influxdb-data:/var/lib/influxdb
    env_file:
      - .env
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=true
    restart: unless-stopped

  ucm-postgres:
    image: postgres:latest
    container_name: ucm-postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-init/init.sh:/docker-entrypoint-initdb.d/init.sh
    env_file:
      - .env
    restart: unless-stopped

volumes:
  influxdb-data:
  postgres-data:
