version: "2"

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - ${INFLUXDB_PORT}:${INFLUXDB_PORT}
    volumes:
      - ./influxdb/data:/var/lib/influxdb
    env_file:
      - .env
    networks:
      - tig-backend
      - tig-frontend
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    depends_on:
      - influxdb
    links:
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    env_file:
      - .env
    networks:
      - tig-backend

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:${GRAFANA_PORT}
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    env_file:
      - .env
    networks:
      - tig-frontend

networks:
  tig-backend:
  tig-frontend: