name: CMake UrbanClimateMonitorPrototype

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install gcc-arm-none-eabi
      run: sudo apt-get install -y gcc-arm-none-eabi

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build/UrbanClimateMonitorPrototype

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE/Software/UrbanClimateMonitorPrototype -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE
