name: Hardware/SensorNode

on:
  push:
    paths:
    - 'Hardware/SensorNode/**.sch'
    - 'Hardware/SensorNode/**.kicad_pcb'

jobs:
  generate-pdfs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: nerdyscout/kicad-exports@v2.1
      with:
        config: docs.kibot.yaml
        dir: docs
        schema: 'Hardware/SensorNode/*.sch'
        board: 'Hardware/SensorNode/*.kicad_pcb'
        
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: hardware-sensornode-docs
        path: docs/*.pdf