name: hardware/sensor-node

on:
  push:
    paths:
    - 'hardware/sensor-node/**.sch'
    - 'hardware/sensor-node/**.kicad_pcb'

jobs:
  generate-pdfs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: nerdyscout/kicad-exports@v2.1
      with:
        config: docs.kibot.yaml
        dir: docs
        schema: 'hardware/sensor-node/*.sch'
        board: 'hardware/sensor-node/*.kicad_pcb'
        
    - uses: nerdyscout/kicad-exports@v2.1
      with:
        config: plot.kibot.yaml
        dir: docs
        
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: hardware_sensor-node_docs
        path: docs/
