name: hardware/sensor-node

on:
  push:
    paths:
    - 'hardware/sensor-node/sensor-node.sch'
    - 'hardware/sensor-node/sensor-node.kicad_pcb'

jobs:
  generate-pdfs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
        persist-credentials: false
        path: repo
        
    - name: Checkout Github Pages branch
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        persist-credentials: false
        path: gh-pages

    - uses: nerdyscout/kicad-exports@v2.2
      with:
        config: ./repo/hardware/kibot-configs/docs.schema.kibot.yaml
        dir: docs
        schema: 'repo/hardware/sensor-node/sensor-node.sch'
        board: 'repo/hardware/sensor-node/sensor-node.kicad_pcb'
    
    - uses: nerdyscout/kicad-exports@v2.2
      with:
        config: ./repo/hardware/kibot-configs/plot.aisler.kibot.yaml
        dir: docs
        schema: 'repo/hardware/sensor-node/sensor-node.sch'
        board: 'repo/hardware/sensor-node/sensor-node.kicad_pcb'

    - name: Copy Artifacts to Github Pages Branch
      run: |
        mkdir -p gh-pages/assets/hardware/schematics/
        mkdir -p gh-pages/assets/hardware/plots/
        cp docs/docs/sensor-node-schematic.pdf gh-pages/assets/hardware/schematics/
        cp docs/docs/img/sensor-node-schematic.svg gh-pages/assets/hardware/schematics/
        cp docs/docs/img/sensor-node-top.svg gh-pages/assets/hardware/plots/
        cp docs/docs/img/sensor-node-bottom.svg gh-pages/assets/hardware/plots/

    - name: Commit Artifacts to Github Pages Branch
      working-directory: './gh-pages'
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add -A
        git commit -m "Deploying hardware artifcats to gh-pages from ${{ github.repository }}@${{ github.sha }}" -a

    - name: Push to Github Pages Branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        directory: './gh-pages'
