name: software/backend

on:
  push:
    paths:
      - 'software/backend/**'

env:
  INFLUXDB_HOST: localhost
  INFLUXDB_PORT: 8086
  INFLUXDB_DB: metrics
  INFLUXDB_ADMIN_USER: admin
  INFLUXDB_ADMIN_PASSWORD: inlufxdb-admin-test-pass
  INFLUXDB_USER: user
  INFLUXDB_USER_PASSWORD: inlufxdb-user-test-pass
  POSTGRES_HOST: localhost
  POSTGRES_PORT: 5432
  POSTGRES_USER: user
  POSTGRES_PASSWORD: postgres-user-test-pass
  POSTGRES_DB: ucm
  POSTGRES_TEST_DB: ucmtest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15

    - name: Write .env File
      working-directory: ./deployment/local-test
      run: |
          echo "INFLUXDB_HOST=${INFLUXDB_HOST}" >> .env
          echo "INFLUXDB_PORT=${INFLUXDB_PORT}" >> .env
          echo "INFLUXDB_TEST_DB=${INFLUXDB_TEST_DB}" >> .env
          echo "INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}" >> .env
          echo "INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}" >> .env
          echo "INFLUXDB_USER=${INFLUXDB_USER}" >> .env
          echo "INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD}" >> .env
          echo "POSTGRES_HOST=${POSTGRES_HOST}" >> .env
          echo "POSTGRES_PORT=${POSTGRES_PORT}" >> .env
          echo "POSTGRES_USER=${POSTGRES_USER}" >> .env
          echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}" >> .env
          echo "POSTGRES_TEST_DB=${POSTGRES_TEST_DB}" >> .env

    - name: Start Development Environment
      working-directory: ./deployment/local-test
      run: |
          chmod +x deploy-local-test.sh
          ./deploy-local-test.sh

    - name: Execute Maven Tests
      working-directory: ./software/backend
      run: mvn test --no-transfer-progress
